title: twelfth key
author: Elliot Vosburgh

url: "https://0evv.github.io"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://0evv.github.io"
footer_text: "twelfth key // writings on science and history"

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.svg

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Subjects"
   link: "tags"
